version: '3.8'
services:
  db:
    image: mysql
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=YOURPASSWORD
        - MYSQL_DATABASE=greencheap
    volumes:
        - ~/greencheap/mysql:/var/lib/mysql
  greencheap:
    image: greencheap/greencheap
    ports:
        - "8080:80"
    links:
        - db:db
    volumes:
        - ~/greencheap/storage:/greencheap/storage
        - ~/greencheap/app/cache:/greencheap/app/cache
