FROM ubuntu:focal
LABEL maintainer="Support@greencheap.net"

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install \
    systemd \
    unzip \
    wget \
    ca-certificates \
    php php-cli php-json php-mysql php-curl php-xml php-zip php-sqlite3 \
    nginx php-fpm

RUN mkdir /greencheap
WORKDIR /greencheap
VOLUME ["/greencheap/storage", "/greencheap/app/cache"]

RUN wget https://greencheap.net/version/download/forced -O /greencheap/greencheap.zip && \
    unzip /greencheap/greencheap.zip && rm /greencheap/greencheap.zip

ADD nginx.conf /etc/nginx/nginx.conf

RUN chown -R www-data: /greencheap && \
    apt-get autoremove wget unzip -y && \
    apt-get autoclean -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["sh", "-c", "service php7.4-fpm restart && nginx"]