FROM ubuntu:trusty
LABEL maintainer="Support@greencheap.net"

RUN apt-get update && \
    apt-get -y install \
    nginx \
    unzip \
    wget \
    ca-certificates \
    php7.4 php7.4-fpm php7.4-cli php7.4-json php7.4-mysql php7.4-curl

RUN mkdir /greencheap
WORKDIR /greencheap
VOLUME ["/greencheap/storage", "/greencheap/app/cache"]

RUN wget https://greencheap.net/version/download/forced -O /greencheap/greencheap.zip && \
    unzip /greencheap/greencheap.zip && rm /greencheap/greencheap.zip

ADD nginx.conf /etc/nginx/nginx.conf

RUN chown -R www-data: /greencheap && \
    apt-get autoremove wget unzip -y && \
    apt-get autoclean -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["sh", "-c", "service php7.4-fpm start && nginx"]
